name: Deploy to AWS S3

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'

    # Install backend dependencies
    - name: Install backend dependencies
      run: npm install

    # Install frontend dependencies
    - name: Install frontend dependencies
      run: |
        cd client
        npm install

    # Build the frontend app
    - name: Build the frontend app
      env:
        CI: false
      run: |
        cd client
        npm run build  

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --delete
      env:
        CI: false
        AWS_S3_BUCKET: bookswap.sarahnaasportfolio.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2 
        SOURCE_DIR: 'build'  
